import json
import time
from utils import collect_docs

def main():
    docs, authors, tags = collect_docs()

    output = {
        "_comment": "DO NOT TOUCH THIS FILE. Auto-generated by utils/docs/build_index.py",
        "timestamp": int(time.time() * 1000),
        "filters": {
            "author": authors,
            "tag": tags,
        },
        "docs": docs,
    }

    with open("docs/data.json", "w", encoding="utf-8") as f:
        json.dump(output, f, indent=4)

    print("[=== indexed successfully ===]")

if __name__ == "__main__":
    main()
